/* 
 * Fingerprint Pro Server API
 *
 * Fingerprint Pro Server API allows you to get information about visitors and about individual events in a server environment. This API can be used for data exports, decision-making, and data analysis scenarios.
 *
 * OpenAPI spec version: 3
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace sdk.Model;

/// <summary>
///     Contains event from activated products - Fingerprint Pro or Bot Detection
/// </summary>
[DataContract]
public class EventResponse : IEquatable<EventResponse>, IValidatableObject
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="EventResponse" /> class.
    /// </summary>
    /// <param name="products">products.</param>
    public EventResponse(ProductsResponse products = default)
    {
        Products = products;
    }

    /// <summary>
    ///     Gets or Sets Products
    /// </summary>
    [DataMember(Name = "products", EmitDefaultValue = false)]
    public ProductsResponse Products { get; set; }

    /// <summary>
    ///     Returns true if EventResponse instances are equal
    /// </summary>
    /// <param name="input">Instance of EventResponse to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(EventResponse input)
    {
        if (input == null)
            return false;

        return
            Products == input.Products ||
            (Products != null &&
             Products.Equals(input.Products));
    }

    /// <summary>
    ///     To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<ValidationResult> IValidatableObject.Validate(
        ValidationContext validationContext)
    {
        yield break;
    }

    /// <summary>
    ///     Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class EventResponse {\n");
        sb.Append("  Products: ").Append(Products).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    ///     Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    ///     Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input)
    {
        return Equals(input as EventResponse);
    }

    /// <summary>
    ///     Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            var hashCode = 41;
            if (Products != null)
                hashCode = hashCode * 59 + Products.GetHashCode();
            return hashCode;
        }
    }
}