// <auto-generated>
/* 
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Fingerprint.ServerSdk.Client;

namespace Fingerprint.ServerSdk.Model
{
    /// <summary>
    /// Filter events by the Bot Detection result, specifically:   &#x60;all&#x60; - events where any kind of bot was detected.   &#x60;good&#x60; - events where a good bot was detected.   &#x60;bad&#x60; - events where a bad bot was detected.   &#x60;none&#x60; - events where no bot was detected. &gt; Note: When using this parameter, only events with the &#x60;botd.bot&#x60; property set to a valid value are returned. Events without a &#x60;botd&#x60; Smart Signal result are left out of the response. 
    /// </summary>
    /// <value>Filter events by the Bot Detection result, specifically:   &#x60;all&#x60; - events where any kind of bot was detected.   &#x60;good&#x60; - events where a good bot was detected.   &#x60;bad&#x60; - events where a bad bot was detected.   &#x60;none&#x60; - events where no bot was detected. &gt; Note: When using this parameter, only events with the &#x60;botd.bot&#x60; property set to a valid value are returned. Events without a &#x60;botd&#x60; Smart Signal result are left out of the response. </value>
    public enum BotFilter
    {
        /// <summary>
        /// Enum All for value: all
        /// </summary>
        All = 1,

        /// <summary>
        /// Enum Good for value: good
        /// </summary>
        Good = 2,

        /// <summary>
        /// Enum Bad for value: bad
        /// </summary>
        Bad = 3,

        /// <summary>
        /// Enum None for value: none
        /// </summary>
        None = 4
    }

    /// <summary>
    /// Converts <see cref="BotFilter"/> to and from the JSON value
    /// </summary>
    public static class BotFilterValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="BotFilter"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static BotFilter FromString(string value)
        {
            if (value.Equals("all"))
                return BotFilter.All;

            if (value.Equals("good"))
                return BotFilter.Good;

            if (value.Equals("bad"))
                return BotFilter.Bad;

            if (value.Equals("none"))
                return BotFilter.None;

            throw new NotImplementedException($"Could not convert value to type BotFilter: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="BotFilter"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static BotFilter? FromStringOrDefault(string value)
        {
            if (value.Equals("all"))
                return BotFilter.All;

            if (value.Equals("good"))
                return BotFilter.Good;

            if (value.Equals("bad"))
                return BotFilter.Bad;

            if (value.Equals("none"))
                return BotFilter.None;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="BotFilter"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(BotFilter value)
        {
            if (value == BotFilter.All)
                return "all";

            if (value == BotFilter.Good)
                return "good";

            if (value == BotFilter.Bad)
                return "bad";

            if (value == BotFilter.None)
                return "none";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BotFilter"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class BotFilterJsonConverter : JsonConverter<BotFilter>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override BotFilter Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            BotFilter? result = rawValue == null
                ? null
                : BotFilterValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the BotFilter to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="botFilter"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, BotFilter botFilter, JsonSerializerOptions options)
        {
            writer.WriteStringValue(BotFilterValueConverter.ToJsonValue(botFilter).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BotFilter"/>
    /// </summary>
    public class BotFilterNullableJsonConverter : JsonConverter<BotFilter?>
    {
        /// <summary>
        /// Returns a BotFilter from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override BotFilter? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            BotFilter? result = rawValue == null
                ? null
                : BotFilterValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the BotFilter to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="botFilter"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, BotFilter? botFilter, JsonSerializerOptions options)
        {
            writer.WriteStringValue(botFilter.HasValue ? BotFilterValueConverter.ToJsonValue(botFilter.Value).ToString() : "null");
        }
    }
}
