// <auto-generated>
/* 
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Fingerprint.ServerSdk.Client;

namespace Fingerprint.ServerSdk.Model
{
    /// <summary>
    /// Bot detection result:  * &#x60;bad&#x60; - bad bot detected, such as Selenium, Puppeteer, Playwright, headless browsers, and so on  * &#x60;good&#x60; - good bot detected, such as Google bot, Baidu Spider, AlexaBot and so on  * &#x60;not_detected&#x60; - the visitor is not a bot 
    /// </summary>
    /// <value>Bot detection result:  * &#x60;bad&#x60; - bad bot detected, such as Selenium, Puppeteer, Playwright, headless browsers, and so on  * &#x60;good&#x60; - good bot detected, such as Google bot, Baidu Spider, AlexaBot and so on  * &#x60;not_detected&#x60; - the visitor is not a bot </value>
    public enum BotResult
    {
        /// <summary>
        /// Enum Bad for value: bad
        /// </summary>
        Bad = 1,

        /// <summary>
        /// Enum Good for value: good
        /// </summary>
        Good = 2,

        /// <summary>
        /// Enum NotDetected for value: not_detected
        /// </summary>
        NotDetected = 3
    }

    /// <summary>
    /// Converts <see cref="BotResult"/> to and from the JSON value
    /// </summary>
    public static class BotResultValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="BotResult"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static BotResult FromString(string value)
        {
            if (value.Equals("bad"))
                return BotResult.Bad;

            if (value.Equals("good"))
                return BotResult.Good;

            if (value.Equals("not_detected"))
                return BotResult.NotDetected;

            throw new NotImplementedException($"Could not convert value to type BotResult: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="BotResult"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static BotResult? FromStringOrDefault(string value)
        {
            if (value.Equals("bad"))
                return BotResult.Bad;

            if (value.Equals("good"))
                return BotResult.Good;

            if (value.Equals("not_detected"))
                return BotResult.NotDetected;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="BotResult"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(BotResult value)
        {
            if (value == BotResult.Bad)
                return "bad";

            if (value == BotResult.Good)
                return "good";

            if (value == BotResult.NotDetected)
                return "not_detected";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BotResult"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class BotResultJsonConverter : JsonConverter<BotResult>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override BotResult Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            BotResult? result = rawValue == null
                ? null
                : BotResultValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the BotResult to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="botResult"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, BotResult botResult, JsonSerializerOptions options)
        {
            writer.WriteStringValue(BotResultValueConverter.ToJsonValue(botResult).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BotResult"/>
    /// </summary>
    public class BotResultNullableJsonConverter : JsonConverter<BotResult?>
    {
        /// <summary>
        /// Returns a BotResult from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override BotResult? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            BotResult? result = rawValue == null
                ? null
                : BotResultValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the BotResult to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="botResult"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, BotResult? botResult, JsonSerializerOptions options)
        {
            writer.WriteStringValue(botResult.HasValue ? BotResultValueConverter.ToJsonValue(botResult.Value).ToString() : "null");
        }
    }
}
