// <auto-generated>
/* 
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Fingerprint.ServerSdk.Client;

namespace Fingerprint.ServerSdk.Model
{
    /// <summary>
    /// Informs the client that the request should be forwarded to the origin with optional request header modifications.
    /// </summary>
    public partial class EventRuleActionAllow : IValidatableObject
    {


        /// <summary>
        /// Initializes a new instance of the <see cref="EventRuleActionAllow" /> class.
        /// </summary>
        /// <param name="type">type (required).</param>
        /// <param name="requestHeaderModifications">requestHeaderModifications.</param>
        [JsonConstructor]
        public EventRuleActionAllow(RuleActionType type, Option<RequestHeaderModifications> requestHeaderModifications = default)
        {
            Type = type;
            RequestHeaderModificationsOption = requestHeaderModifications;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public RuleActionType Type { get; set; }

        /// <summary>
        /// Used to track the state of RequestHeaderModifications
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<RequestHeaderModifications> RequestHeaderModificationsOption { get; private set; }

        /// <summary>
        /// Gets or Sets RequestHeaderModifications
        /// </summary>
        [JsonPropertyName("request_header_modifications")]
        public RequestHeaderModifications RequestHeaderModifications { get { return this.RequestHeaderModificationsOption; } set { this.RequestHeaderModificationsOption = new Option<RequestHeaderModifications>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EventRuleActionAllow {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  RequestHeaderModifications: ").Append(RequestHeaderModifications).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EventRuleActionAllow" />
    /// </summary>
    public class EventRuleActionAllowJsonConverter : JsonConverter<EventRuleActionAllow>
    {
        /// <summary>
        /// Deserializes json to <see cref="EventRuleActionAllow" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EventRuleActionAllow Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<RuleActionType?> type = default;
            Option<RequestHeaderModifications> requestHeaderModifications = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "type":
                            string typeRawValue = utf8JsonReader.GetString();
                            if (typeRawValue != null)
                                type = new Option<RuleActionType?>(RuleActionTypeValueConverter.FromStringOrDefault(typeRawValue));
                            break;
                        case "request_header_modifications":
                            requestHeaderModifications = new Option<RequestHeaderModifications>(JsonSerializer.Deserialize<RequestHeaderModifications>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class EventRuleActionAllow.", nameof(type));

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class EventRuleActionAllow.");

            if (requestHeaderModifications.IsSet && requestHeaderModifications.Value == null)
                throw new ArgumentNullException(nameof(requestHeaderModifications), "Property is not nullable for class EventRuleActionAllow.");

            return new EventRuleActionAllow(type.Value.Value, requestHeaderModifications);
        }

        /// <summary>
        /// Serializes a <see cref="EventRuleActionAllow" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="eventRuleActionAllow"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EventRuleActionAllow eventRuleActionAllow, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, eventRuleActionAllow, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EventRuleActionAllow" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="eventRuleActionAllow"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EventRuleActionAllow eventRuleActionAllow, JsonSerializerOptions jsonSerializerOptions)
        {
            if (eventRuleActionAllow.RequestHeaderModificationsOption.IsSet && eventRuleActionAllow.RequestHeaderModifications == null)
                throw new ArgumentNullException(nameof(eventRuleActionAllow.RequestHeaderModifications), "Property is required for class EventRuleActionAllow.");

            var typeRawValue = RuleActionTypeValueConverter.ToJsonValue(eventRuleActionAllow.Type);
            writer.WriteString("type", typeRawValue);

            if (eventRuleActionAllow.RequestHeaderModificationsOption.IsSet)
            {
                writer.WritePropertyName("request_header_modifications");
                JsonSerializer.Serialize(writer, eventRuleActionAllow.RequestHeaderModifications, jsonSerializerOptions);
            }
        }
    }
}
