/* 
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * OpenAPI spec version: 3
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Text;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;
using System.Text.Json;
using Fingerprint.ServerSdk.Json;

namespace Fingerprint.ServerSdk.Model
{
    /// <summary>
    /// Contains results from all activated products - Fingerprint Pro, Bot Detection, and others.
    /// </summary>
    [DataContract]
    public class EventsGetResponse : IEquatable<EventsGetResponse>
    {


        /// <summary>
        /// Initializes a new instance of the <see cref="EventsGetResponse" /> class.
        /// </summary>
        /// <param name="products">products (required).</param>
        public EventsGetResponse(Products products = default(Products))
        {
            // to ensure "products" is required (not null)
            // swagger debug: EventsGetResponse Products

            if (products == null)
            {
                throw new InvalidDataException("products is a required property for EventsGetResponse and cannot be null");
            }
            else
            {
                this.Products = products;
            }
        }

        /// <summary>
        /// Gets or Sets Products
        /// </summary>
        [DataMember(Name = "products", EmitDefaultValue = false)]
        [JsonPropertyName("products")]
        public Products Products { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EventsGetResponse {\n");
            sb.Append("  Products: ").Append(Products).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonUtils.Serialize(this);
        }

        /// <summary>
        /// Returns true if EventsGetResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of EventsGetResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EventsGetResponse? input)
        {
            if (input == null)
                return false;

            return
                (
                this.Products == input.Products ||
                (this.Products != null &&
                this.Products.Equals(input.Products))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Products != null)
                    hashCode = hashCode * 59 + this.Products.GetHashCode();
                return hashCode;
            }
        }

    }
}
