// <auto-generated>
/* 
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Fingerprint.ServerSdk.Client;

namespace Fingerprint.ServerSdk.Model
{
    /// <summary>
    /// Baseline measurement of canonical fonts rendered on the device. Numeric width metrics, in CSS pixels, for the canonical fonts collected by the agent. 
    /// </summary>
    public partial class FontPreferences : IValidatableObject
    {


        /// <summary>
        /// Initializes a new instance of the <see cref="FontPreferences" /> class.
        /// </summary>
        /// <param name="default">default.</param>
        /// <param name="serif">serif.</param>
        /// <param name="sans">sans.</param>
        /// <param name="mono">mono.</param>
        /// <param name="apple">apple.</param>
        /// <param name="min">min.</param>
        /// <param name="system">system.</param>
        [JsonConstructor]
        public FontPreferences(Option<double?> @default = default, Option<double?> serif = default, Option<double?> sans = default, Option<double?> mono = default, Option<double?> apple = default, Option<double?> min = default, Option<double?> @system = default)
        {
            DefaultOption = @default;
            SerifOption = serif;
            SansOption = sans;
            MonoOption = mono;
            AppleOption = apple;
            MinOption = min;
            SystemOption = @system;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Default
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> DefaultOption { get; private set; }

        /// <summary>
        /// Gets or Sets Default
        /// </summary>
        [JsonPropertyName("default")]
        public double? Default { get { return this.DefaultOption; } set { this.DefaultOption = new Option<double?>(value); } }

        /// <summary>
        /// Used to track the state of Serif
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> SerifOption { get; private set; }

        /// <summary>
        /// Gets or Sets Serif
        /// </summary>
        [JsonPropertyName("serif")]
        public double? Serif { get { return this.SerifOption; } set { this.SerifOption = new Option<double?>(value); } }

        /// <summary>
        /// Used to track the state of Sans
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> SansOption { get; private set; }

        /// <summary>
        /// Gets or Sets Sans
        /// </summary>
        [JsonPropertyName("sans")]
        public double? Sans { get { return this.SansOption; } set { this.SansOption = new Option<double?>(value); } }

        /// <summary>
        /// Used to track the state of Mono
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> MonoOption { get; private set; }

        /// <summary>
        /// Gets or Sets Mono
        /// </summary>
        [JsonPropertyName("mono")]
        public double? Mono { get { return this.MonoOption; } set { this.MonoOption = new Option<double?>(value); } }

        /// <summary>
        /// Used to track the state of Apple
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> AppleOption { get; private set; }

        /// <summary>
        /// Gets or Sets Apple
        /// </summary>
        [JsonPropertyName("apple")]
        public double? Apple { get { return this.AppleOption; } set { this.AppleOption = new Option<double?>(value); } }

        /// <summary>
        /// Used to track the state of Min
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> MinOption { get; private set; }

        /// <summary>
        /// Gets or Sets Min
        /// </summary>
        [JsonPropertyName("min")]
        public double? Min { get { return this.MinOption; } set { this.MinOption = new Option<double?>(value); } }

        /// <summary>
        /// Used to track the state of System
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> SystemOption { get; private set; }

        /// <summary>
        /// Gets or Sets System
        /// </summary>
        [JsonPropertyName("system")]
        public double? System { get { return this.SystemOption; } set { this.SystemOption = new Option<double?>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FontPreferences {\n");
            sb.Append("  Default: ").Append(Default).Append("\n");
            sb.Append("  Serif: ").Append(Serif).Append("\n");
            sb.Append("  Sans: ").Append(Sans).Append("\n");
            sb.Append("  Mono: ").Append(Mono).Append("\n");
            sb.Append("  Apple: ").Append(Apple).Append("\n");
            sb.Append("  Min: ").Append(Min).Append("\n");
            sb.Append("  System: ").Append(System).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="FontPreferences" />
    /// </summary>
    public class FontPreferencesJsonConverter : JsonConverter<FontPreferences>
    {
        /// <summary>
        /// Deserializes json to <see cref="FontPreferences" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override FontPreferences Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<double?> varDefault = default;
            Option<double?> serif = default;
            Option<double?> sans = default;
            Option<double?> mono = default;
            Option<double?> apple = default;
            Option<double?> min = default;
            Option<double?> varSystem = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "default":
                            varDefault = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "serif":
                            serif = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "sans":
                            sans = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "mono":
                            mono = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "apple":
                            apple = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "min":
                            min = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "system":
                            varSystem = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (varDefault.IsSet && varDefault.Value == null)
                throw new ArgumentNullException(nameof(varDefault), "Property is not nullable for class FontPreferences.");

            if (serif.IsSet && serif.Value == null)
                throw new ArgumentNullException(nameof(serif), "Property is not nullable for class FontPreferences.");

            if (sans.IsSet && sans.Value == null)
                throw new ArgumentNullException(nameof(sans), "Property is not nullable for class FontPreferences.");

            if (mono.IsSet && mono.Value == null)
                throw new ArgumentNullException(nameof(mono), "Property is not nullable for class FontPreferences.");

            if (apple.IsSet && apple.Value == null)
                throw new ArgumentNullException(nameof(apple), "Property is not nullable for class FontPreferences.");

            if (min.IsSet && min.Value == null)
                throw new ArgumentNullException(nameof(min), "Property is not nullable for class FontPreferences.");

            if (varSystem.IsSet && varSystem.Value == null)
                throw new ArgumentNullException(nameof(varSystem), "Property is not nullable for class FontPreferences.");

            return new FontPreferences(varDefault, serif, sans, mono, apple, min, varSystem);
        }

        /// <summary>
        /// Serializes a <see cref="FontPreferences" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="fontPreferences"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, FontPreferences fontPreferences, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, fontPreferences, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="FontPreferences" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="fontPreferences"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, FontPreferences fontPreferences, JsonSerializerOptions jsonSerializerOptions)
        {
            if (fontPreferences.DefaultOption.IsSet)
                writer.WriteNumber("default", fontPreferences.DefaultOption.Value.Value);

            if (fontPreferences.SerifOption.IsSet)
                writer.WriteNumber("serif", fontPreferences.SerifOption.Value.Value);

            if (fontPreferences.SansOption.IsSet)
                writer.WriteNumber("sans", fontPreferences.SansOption.Value.Value);

            if (fontPreferences.MonoOption.IsSet)
                writer.WriteNumber("mono", fontPreferences.MonoOption.Value.Value);

            if (fontPreferences.AppleOption.IsSet)
                writer.WriteNumber("apple", fontPreferences.AppleOption.Value.Value);

            if (fontPreferences.MinOption.IsSet)
                writer.WriteNumber("min", fontPreferences.MinOption.Value.Value);

            if (fontPreferences.SystemOption.IsSet)
                writer.WriteNumber("system", fontPreferences.SystemOption.Value.Value);
        }
    }
}
