// <auto-generated>
/* 
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Fingerprint.ServerSdk.Client;

namespace Fingerprint.ServerSdk.Model
{
    /// <summary>
    /// GeolocationSubdivisionsInner
    /// </summary>
    public partial class GeolocationSubdivisionsInner : IValidatableObject
    {


        /// <summary>
        /// Initializes a new instance of the <see cref="GeolocationSubdivisionsInner" /> class.
        /// </summary>
        /// <param name="isoCode">isoCode (required).</param>
        /// <param name="name">name (required).</param>
        [JsonConstructor]
        public GeolocationSubdivisionsInner(string isoCode, string name)
        {
            IsoCode = isoCode;
            Name = name;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets IsoCode
        /// </summary>
        [JsonPropertyName("iso_code")]
        public string IsoCode { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GeolocationSubdivisionsInner {\n");
            sb.Append("  IsoCode: ").Append(IsoCode).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GeolocationSubdivisionsInner" />
    /// </summary>
    public class GeolocationSubdivisionsInnerJsonConverter : JsonConverter<GeolocationSubdivisionsInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="GeolocationSubdivisionsInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GeolocationSubdivisionsInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> isoCode = default;
            Option<string> name = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "iso_code":
                            isoCode = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "name":
                            name = new Option<string>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!isoCode.IsSet)
                throw new ArgumentException("Property is required for class GeolocationSubdivisionsInner.", nameof(isoCode));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class GeolocationSubdivisionsInner.", nameof(name));

            if (isoCode.IsSet && isoCode.Value == null)
                throw new ArgumentNullException(nameof(isoCode), "Property is not nullable for class GeolocationSubdivisionsInner.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class GeolocationSubdivisionsInner.");

            return new GeolocationSubdivisionsInner(isoCode.Value, name.Value);
        }

        /// <summary>
        /// Serializes a <see cref="GeolocationSubdivisionsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="geolocationSubdivisionsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GeolocationSubdivisionsInner geolocationSubdivisionsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, geolocationSubdivisionsInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GeolocationSubdivisionsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="geolocationSubdivisionsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GeolocationSubdivisionsInner geolocationSubdivisionsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (geolocationSubdivisionsInner.IsoCode == null)
                throw new ArgumentNullException(nameof(geolocationSubdivisionsInner.IsoCode), "Property is required for class GeolocationSubdivisionsInner.");

            if (geolocationSubdivisionsInner.Name == null)
                throw new ArgumentNullException(nameof(geolocationSubdivisionsInner.Name), "Property is required for class GeolocationSubdivisionsInner.");

            writer.WriteString("iso_code", geolocationSubdivisionsInner.IsoCode);

            writer.WriteString("name", geolocationSubdivisionsInner.Name);
        }
    }
}
