// <auto-generated>
/* 
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Fingerprint.ServerSdk.Client;

namespace Fingerprint.ServerSdk.Model
{
    /// <summary>
    /// Integration
    /// </summary>
    public partial class Integration : IValidatableObject
    {


        /// <summary>
        /// Initializes a new instance of the <see cref="Integration" /> class.
        /// </summary>
        /// <param name="name">The name of the specific integration, e.g. \"fingerprint-pro-react\"..</param>
        /// <param name="varVersion">The version of the specific integration, e.g. \"3.11.10\"..</param>
        /// <param name="subintegration">subintegration.</param>
        [JsonConstructor]
        public Integration(Option<string> name = default, Option<string> varVersion = default, Option<IntegrationSubintegration> subintegration = default)
        {
            NameOption = name;
            VarVersionOption = varVersion;
            SubintegrationOption = subintegration;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> NameOption { get; private set; }

        /// <summary>
        /// The name of the specific integration, e.g. \"fingerprint-pro-react\".
        /// </summary>
        /// <value>The name of the specific integration, e.g. \"fingerprint-pro-react\".</value>
        [JsonPropertyName("name")]
        public string Name { get { return this.NameOption; } set { this.NameOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of VarVersion
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> VarVersionOption { get; private set; }

        /// <summary>
        /// The version of the specific integration, e.g. \"3.11.10\".
        /// </summary>
        /// <value>The version of the specific integration, e.g. \"3.11.10\".</value>
        [JsonPropertyName("version")]
        public string VarVersion { get { return this.VarVersionOption; } set { this.VarVersionOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Subintegration
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<IntegrationSubintegration> SubintegrationOption { get; private set; }

        /// <summary>
        /// Gets or Sets Subintegration
        /// </summary>
        [JsonPropertyName("subintegration")]
        public IntegrationSubintegration Subintegration { get { return this.SubintegrationOption; } set { this.SubintegrationOption = new Option<IntegrationSubintegration>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Integration {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  VarVersion: ").Append(VarVersion).Append("\n");
            sb.Append("  Subintegration: ").Append(Subintegration).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Integration" />
    /// </summary>
    public class IntegrationJsonConverter : JsonConverter<Integration>
    {
        /// <summary>
        /// Deserializes json to <see cref="Integration" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Integration Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> name = default;
            Option<string> varVersion = default;
            Option<IntegrationSubintegration> subintegration = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "version":
                            varVersion = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "subintegration":
                            subintegration = new Option<IntegrationSubintegration>(JsonSerializer.Deserialize<IntegrationSubintegration>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class Integration.");

            if (varVersion.IsSet && varVersion.Value == null)
                throw new ArgumentNullException(nameof(varVersion), "Property is not nullable for class Integration.");

            if (subintegration.IsSet && subintegration.Value == null)
                throw new ArgumentNullException(nameof(subintegration), "Property is not nullable for class Integration.");

            return new Integration(name, varVersion, subintegration);
        }

        /// <summary>
        /// Serializes a <see cref="Integration" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="integration"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Integration integration, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, integration, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Integration" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="integration"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Integration integration, JsonSerializerOptions jsonSerializerOptions)
        {
            if (integration.NameOption.IsSet && integration.Name == null)
                throw new ArgumentNullException(nameof(integration.Name), "Property is required for class Integration.");

            if (integration.VarVersionOption.IsSet && integration.VarVersion == null)
                throw new ArgumentNullException(nameof(integration.VarVersion), "Property is required for class Integration.");

            if (integration.SubintegrationOption.IsSet && integration.Subintegration == null)
                throw new ArgumentNullException(nameof(integration.Subintegration), "Property is required for class Integration.");

            if (integration.NameOption.IsSet)
                writer.WriteString("name", integration.Name);

            if (integration.VarVersionOption.IsSet)
                writer.WriteString("version", integration.VarVersion);

            if (integration.SubintegrationOption.IsSet)
            {
                writer.WritePropertyName("subintegration");
                JsonSerializer.Serialize(writer, integration.Subintegration, jsonSerializerOptions);
            }
        }
    }
}
