// <auto-generated>
/* 
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Fingerprint.ServerSdk.Client;

namespace Fingerprint.ServerSdk.Model
{
    /// <summary>
    /// IPBlockList
    /// </summary>
    public partial class IPBlockList : IValidatableObject
    {


        /// <summary>
        /// Initializes a new instance of the <see cref="IPBlockList" /> class.
        /// </summary>
        /// <param name="emailSpam">IP address was part of a known email spam attack (SMTP)..</param>
        /// <param name="attackSource">IP address was part of a known network attack (SSH/HTTPS)..</param>
        /// <param name="torNode">IP address was part of known TOR network activity..</param>
        [JsonConstructor]
        public IPBlockList(Option<bool?> emailSpam = default, Option<bool?> attackSource = default, Option<bool?> torNode = default)
        {
            EmailSpamOption = emailSpam;
            AttackSourceOption = attackSource;
            TorNodeOption = torNode;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of EmailSpam
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> EmailSpamOption { get; private set; }

        /// <summary>
        /// IP address was part of a known email spam attack (SMTP).
        /// </summary>
        /// <value>IP address was part of a known email spam attack (SMTP).</value>
        [JsonPropertyName("email_spam")]
        public bool? EmailSpam { get { return this.EmailSpamOption; } set { this.EmailSpamOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of AttackSource
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> AttackSourceOption { get; private set; }

        /// <summary>
        /// IP address was part of a known network attack (SSH/HTTPS).
        /// </summary>
        /// <value>IP address was part of a known network attack (SSH/HTTPS).</value>
        [JsonPropertyName("attack_source")]
        public bool? AttackSource { get { return this.AttackSourceOption; } set { this.AttackSourceOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of TorNode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> TorNodeOption { get; private set; }

        /// <summary>
        /// IP address was part of known TOR network activity.
        /// </summary>
        /// <value>IP address was part of known TOR network activity.</value>
        [JsonPropertyName("tor_node")]
        public bool? TorNode { get { return this.TorNodeOption; } set { this.TorNodeOption = new Option<bool?>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class IPBlockList {\n");
            sb.Append("  EmailSpam: ").Append(EmailSpam).Append("\n");
            sb.Append("  AttackSource: ").Append(AttackSource).Append("\n");
            sb.Append("  TorNode: ").Append(TorNode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="IPBlockList" />
    /// </summary>
    public class IPBlockListJsonConverter : JsonConverter<IPBlockList>
    {
        /// <summary>
        /// Deserializes json to <see cref="IPBlockList" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override IPBlockList Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> emailSpam = default;
            Option<bool?> attackSource = default;
            Option<bool?> torNode = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "email_spam":
                            emailSpam = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "attack_source":
                            attackSource = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "tor_node":
                            torNode = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (emailSpam.IsSet && emailSpam.Value == null)
                throw new ArgumentNullException(nameof(emailSpam), "Property is not nullable for class IPBlockList.");

            if (attackSource.IsSet && attackSource.Value == null)
                throw new ArgumentNullException(nameof(attackSource), "Property is not nullable for class IPBlockList.");

            if (torNode.IsSet && torNode.Value == null)
                throw new ArgumentNullException(nameof(torNode), "Property is not nullable for class IPBlockList.");

            return new IPBlockList(emailSpam, attackSource, torNode);
        }

        /// <summary>
        /// Serializes a <see cref="IPBlockList" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="iPBlockList"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, IPBlockList iPBlockList, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, iPBlockList, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="IPBlockList" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="iPBlockList"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, IPBlockList iPBlockList, JsonSerializerOptions jsonSerializerOptions)
        {
            if (iPBlockList.EmailSpamOption.IsSet)
                writer.WriteBoolean("email_spam", iPBlockList.EmailSpamOption.Value.Value);

            if (iPBlockList.AttackSourceOption.IsSet)
                writer.WriteBoolean("attack_source", iPBlockList.AttackSourceOption.Value.Value);

            if (iPBlockList.TorNodeOption.IsSet)
                writer.WriteBoolean("tor_node", iPBlockList.TorNodeOption.Value.Value);
        }
    }
}
