// <auto-generated>
/* 
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Fingerprint.ServerSdk.Client;

namespace Fingerprint.ServerSdk.Model
{
    /// <summary>
    /// Confidence level of the proxy detection. If a proxy is not detected, confidence is \&quot;high\&quot;. If it&#39;s detected, can be \&quot;low\&quot;, \&quot;medium\&quot;, or \&quot;high\&quot;. 
    /// </summary>
    /// <value>Confidence level of the proxy detection. If a proxy is not detected, confidence is \&quot;high\&quot;. If it&#39;s detected, can be \&quot;low\&quot;, \&quot;medium\&quot;, or \&quot;high\&quot;. </value>
    public enum ProxyConfidence
    {
        /// <summary>
        /// Enum Low for value: low
        /// </summary>
        Low = 1,

        /// <summary>
        /// Enum Medium for value: medium
        /// </summary>
        Medium = 2,

        /// <summary>
        /// Enum High for value: high
        /// </summary>
        High = 3
    }

    /// <summary>
    /// Converts <see cref="ProxyConfidence"/> to and from the JSON value
    /// </summary>
    public static class ProxyConfidenceValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="ProxyConfidence"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ProxyConfidence FromString(string value)
        {
            if (value.Equals("low"))
                return ProxyConfidence.Low;

            if (value.Equals("medium"))
                return ProxyConfidence.Medium;

            if (value.Equals("high"))
                return ProxyConfidence.High;

            throw new NotImplementedException($"Could not convert value to type ProxyConfidence: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="ProxyConfidence"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ProxyConfidence? FromStringOrDefault(string value)
        {
            if (value.Equals("low"))
                return ProxyConfidence.Low;

            if (value.Equals("medium"))
                return ProxyConfidence.Medium;

            if (value.Equals("high"))
                return ProxyConfidence.High;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ProxyConfidence"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(ProxyConfidence value)
        {
            if (value == ProxyConfidence.Low)
                return "low";

            if (value == ProxyConfidence.Medium)
                return "medium";

            if (value == ProxyConfidence.High)
                return "high";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ProxyConfidence"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class ProxyConfidenceJsonConverter : JsonConverter<ProxyConfidence>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override ProxyConfidence Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            ProxyConfidence? result = rawValue == null
                ? null
                : ProxyConfidenceValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the ProxyConfidence to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="proxyConfidence"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, ProxyConfidence proxyConfidence, JsonSerializerOptions options)
        {
            writer.WriteStringValue(ProxyConfidenceValueConverter.ToJsonValue(proxyConfidence).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ProxyConfidence"/>
    /// </summary>
    public class ProxyConfidenceNullableJsonConverter : JsonConverter<ProxyConfidence?>
    {
        /// <summary>
        /// Returns a ProxyConfidence from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override ProxyConfidence? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            ProxyConfidence? result = rawValue == null
                ? null
                : ProxyConfidenceValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the ProxyConfidence to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="proxyConfidence"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, ProxyConfidence? proxyConfidence, JsonSerializerOptions options)
        {
            writer.WriteStringValue(proxyConfidence.HasValue ? ProxyConfidenceValueConverter.ToJsonValue(proxyConfidence.Value).ToString() : "null");
        }
    }
}
