// <auto-generated>
/* 
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Fingerprint.ServerSdk.Client;

namespace Fingerprint.ServerSdk.Model
{
    /// <summary>
    /// Proxy detection details (present if `proxy` is `true`)
    /// </summary>
    public partial class ProxyDetails : IValidatableObject
    {


        /// <summary>
        /// Initializes a new instance of the <see cref="ProxyDetails" /> class.
        /// </summary>
        /// <param name="proxyType">Residential proxies use real user IP addresses to appear as legitimate traffic,  while data center proxies are public proxies hosted in data centers  (required).</param>
        /// <param name="lastSeenAt">Unix millisecond timestamp with hourly resolution of when this IP was last seen as a proxy .</param>
        /// <param name="provider">String representing the last proxy service provider detected when this IP was synced. An IP can be shared by multiple service providers. .</param>
        [JsonConstructor]
        public ProxyDetails(ProxyTypeEnum proxyType, Option<long?> lastSeenAt = default, Option<string> provider = default)
        {
            ProxyType = proxyType;
            LastSeenAtOption = lastSeenAt;
            ProviderOption = provider;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Residential proxies use real user IP addresses to appear as legitimate traffic,  while data center proxies are public proxies hosted in data centers 
        /// </summary>
        /// <value>Residential proxies use real user IP addresses to appear as legitimate traffic,  while data center proxies are public proxies hosted in data centers </value>
        public enum ProxyTypeEnum
        {
            /// <summary>
            /// Enum Residential for value: residential
            /// </summary>

            Residential = 1,

            /// <summary>
            /// Enum DataCenter for value: data_center
            /// </summary>

            DataCenter = 2
        }

        /// <summary>
        /// Returns a <see cref="ProxyTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ProxyTypeEnum ProxyTypeEnumFromString(string value)
        {
            if (value.Equals("residential"))
                return ProxyTypeEnum.Residential;

            if (value.Equals("data_center"))
                return ProxyTypeEnum.DataCenter;

            throw new NotImplementedException($"Could not convert value to type ProxyTypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ProxyTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ProxyTypeEnum? ProxyTypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("residential"))
                return ProxyTypeEnum.Residential;

            if (value.Equals("data_center"))
                return ProxyTypeEnum.DataCenter;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ProxyTypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ProxyTypeEnumToJsonValue(ProxyTypeEnum value)
        {
            if (value == ProxyTypeEnum.Residential)
                return "residential";

            if (value == ProxyTypeEnum.DataCenter)
                return "data_center";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Residential proxies use real user IP addresses to appear as legitimate traffic,  while data center proxies are public proxies hosted in data centers 
        /// </summary>
        /// <value>Residential proxies use real user IP addresses to appear as legitimate traffic,  while data center proxies are public proxies hosted in data centers </value>
        [JsonPropertyName("proxy_type")]
        public ProxyTypeEnum ProxyType { get; set; }

        /// <summary>
        /// Used to track the state of LastSeenAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> LastSeenAtOption { get; private set; }

        /// <summary>
        /// Unix millisecond timestamp with hourly resolution of when this IP was last seen as a proxy 
        /// </summary>
        /// <value>Unix millisecond timestamp with hourly resolution of when this IP was last seen as a proxy </value>
        [JsonPropertyName("last_seen_at")]
        public long? LastSeenAt { get { return this.LastSeenAtOption; } set { this.LastSeenAtOption = new Option<long?>(value); } }

        /// <summary>
        /// Used to track the state of Provider
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> ProviderOption { get; private set; }

        /// <summary>
        /// String representing the last proxy service provider detected when this IP was synced. An IP can be shared by multiple service providers. 
        /// </summary>
        /// <value>String representing the last proxy service provider detected when this IP was synced. An IP can be shared by multiple service providers. </value>
        [JsonPropertyName("provider")]
        public string Provider { get { return this.ProviderOption; } set { this.ProviderOption = new Option<string>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProxyDetails {\n");
            sb.Append("  ProxyType: ").Append(ProxyType).Append("\n");
            sb.Append("  LastSeenAt: ").Append(LastSeenAt).Append("\n");
            sb.Append("  Provider: ").Append(Provider).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ProxyDetails" />
    /// </summary>
    public class ProxyDetailsJsonConverter : JsonConverter<ProxyDetails>
    {
        /// <summary>
        /// Deserializes json to <see cref="ProxyDetails" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ProxyDetails Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<ProxyDetails.ProxyTypeEnum?> proxyType = default;
            Option<long?> lastSeenAt = default;
            Option<string> provider = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "proxy_type":
                            string proxyTypeRawValue = utf8JsonReader.GetString();
                            if (proxyTypeRawValue != null)
                                proxyType = new Option<ProxyDetails.ProxyTypeEnum?>(ProxyDetails.ProxyTypeEnumFromStringOrDefault(proxyTypeRawValue));
                            break;
                        case "last_seen_at":
                            lastSeenAt = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "provider":
                            provider = new Option<string>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!proxyType.IsSet)
                throw new ArgumentException("Property is required for class ProxyDetails.", nameof(proxyType));

            if (proxyType.IsSet && proxyType.Value == null)
                throw new ArgumentNullException(nameof(proxyType), "Property is not nullable for class ProxyDetails.");

            if (lastSeenAt.IsSet && lastSeenAt.Value == null)
                throw new ArgumentNullException(nameof(lastSeenAt), "Property is not nullable for class ProxyDetails.");

            if (provider.IsSet && provider.Value == null)
                throw new ArgumentNullException(nameof(provider), "Property is not nullable for class ProxyDetails.");

            return new ProxyDetails(proxyType.Value.Value, lastSeenAt, provider);
        }

        /// <summary>
        /// Serializes a <see cref="ProxyDetails" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="proxyDetails"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ProxyDetails proxyDetails, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, proxyDetails, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ProxyDetails" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="proxyDetails"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ProxyDetails proxyDetails, JsonSerializerOptions jsonSerializerOptions)
        {
            if (proxyDetails.ProviderOption.IsSet && proxyDetails.Provider == null)
                throw new ArgumentNullException(nameof(proxyDetails.Provider), "Property is required for class ProxyDetails.");

            var proxyTypeRawValue = ProxyDetails.ProxyTypeEnumToJsonValue(proxyDetails.ProxyType);
            writer.WriteString("proxy_type", proxyTypeRawValue);
            if (proxyDetails.LastSeenAtOption.IsSet)
                writer.WriteNumber("last_seen_at", proxyDetails.LastSeenAtOption.Value.Value);

            if (proxyDetails.ProviderOption.IsSet)
                writer.WriteString("provider", proxyDetails.Provider);
        }
    }
}
