// <auto-generated>
/* 
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Fingerprint.ServerSdk.Client;

namespace Fingerprint.ServerSdk.Model
{
    /// <summary>
    /// Filter events by the SDK Platform associated with the identification event (&#x60;sdk.platform&#x60; property) . &#x60;js&#x60; - Javascript agent (Web). &#x60;ios&#x60; - Apple iOS based devices. &#x60;android&#x60; - Android based devices. 
    /// </summary>
    /// <value>Filter events by the SDK Platform associated with the identification event (&#x60;sdk.platform&#x60; property) . &#x60;js&#x60; - Javascript agent (Web). &#x60;ios&#x60; - Apple iOS based devices. &#x60;android&#x60; - Android based devices. </value>
    public enum SearchEventsSdkPlatform
    {
        /// <summary>
        /// Enum Js for value: js
        /// </summary>
        Js = 1,

        /// <summary>
        /// Enum Android for value: android
        /// </summary>
        Android = 2,

        /// <summary>
        /// Enum Ios for value: ios
        /// </summary>
        Ios = 3
    }

    /// <summary>
    /// Converts <see cref="SearchEventsSdkPlatform"/> to and from the JSON value
    /// </summary>
    public static class SearchEventsSdkPlatformValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="SearchEventsSdkPlatform"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SearchEventsSdkPlatform FromString(string value)
        {
            if (value.Equals("js"))
                return SearchEventsSdkPlatform.Js;

            if (value.Equals("android"))
                return SearchEventsSdkPlatform.Android;

            if (value.Equals("ios"))
                return SearchEventsSdkPlatform.Ios;

            throw new NotImplementedException($"Could not convert value to type SearchEventsSdkPlatform: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="SearchEventsSdkPlatform"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SearchEventsSdkPlatform? FromStringOrDefault(string value)
        {
            if (value.Equals("js"))
                return SearchEventsSdkPlatform.Js;

            if (value.Equals("android"))
                return SearchEventsSdkPlatform.Android;

            if (value.Equals("ios"))
                return SearchEventsSdkPlatform.Ios;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="SearchEventsSdkPlatform"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(SearchEventsSdkPlatform value)
        {
            if (value == SearchEventsSdkPlatform.Js)
                return "js";

            if (value == SearchEventsSdkPlatform.Android)
                return "android";

            if (value == SearchEventsSdkPlatform.Ios)
                return "ios";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SearchEventsSdkPlatform"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class SearchEventsSdkPlatformJsonConverter : JsonConverter<SearchEventsSdkPlatform>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override SearchEventsSdkPlatform Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            SearchEventsSdkPlatform? result = rawValue == null
                ? null
                : SearchEventsSdkPlatformValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the SearchEventsSdkPlatform to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="searchEventsSdkPlatform"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, SearchEventsSdkPlatform searchEventsSdkPlatform, JsonSerializerOptions options)
        {
            writer.WriteStringValue(SearchEventsSdkPlatformValueConverter.ToJsonValue(searchEventsSdkPlatform).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SearchEventsSdkPlatform"/>
    /// </summary>
    public class SearchEventsSdkPlatformNullableJsonConverter : JsonConverter<SearchEventsSdkPlatform?>
    {
        /// <summary>
        /// Returns a SearchEventsSdkPlatform from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override SearchEventsSdkPlatform? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            SearchEventsSdkPlatform? result = rawValue == null
                ? null
                : SearchEventsSdkPlatformValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the SearchEventsSdkPlatform to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="searchEventsSdkPlatform"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, SearchEventsSdkPlatform? searchEventsSdkPlatform, JsonSerializerOptions options)
        {
            writer.WriteStringValue(searchEventsSdkPlatform.HasValue ? SearchEventsSdkPlatformValueConverter.ToJsonValue(searchEventsSdkPlatform.Value).ToString() : "null");
        }
    }
}
