// <auto-generated>
/* 
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Fingerprint.ServerSdk.Client;

namespace Fingerprint.ServerSdk.Model
{
    /// <summary>
    /// Sums key data points for a specific `visitor_id`, `ip_address` and `linked_id` at three distinct time intervals: 5 minutes, 1 hour, and 24 hours as follows:   - Number of distinct IP addresses associated to the visitor Id. - Number of distinct linked Ids associated with the visitor Id. - Number of distinct countries associated with the visitor Id. - Number of identification events associated with the visitor Id. - Number of identification events associated with the detected IP address. - Number of distinct IP addresses associated with the provided linked Id. - Number of distinct visitor Ids associated with the provided linked Id.  The `24h` interval of `distinct_ip`, `distinct_linked_id`, `distinct_country`, `distinct_ip_by_linked_id` and `distinct_visitor_id_by_linked_id` will be omitted  if the number of `events` for the visitor Id in the last 24 hours (`events.['24h']`) is higher than 20.000.  All will not necessarily be returned in a response, some may be omitted if the  associated event does not have the required data, such as a linked_id. 
    /// </summary>
    public partial class Velocity : IValidatableObject
    {


        /// <summary>
        /// Initializes a new instance of the <see cref="Velocity" /> class.
        /// </summary>
        /// <param name="distinctIp">distinctIp.</param>
        /// <param name="distinctLinkedId">distinctLinkedId.</param>
        /// <param name="distinctCountry">distinctCountry.</param>
        /// <param name="events">events.</param>
        /// <param name="ipEvents">ipEvents.</param>
        /// <param name="distinctIpByLinkedId">distinctIpByLinkedId.</param>
        /// <param name="distinctVisitorIdByLinkedId">distinctVisitorIdByLinkedId.</param>
        [JsonConstructor]
        public Velocity(Option<VelocityData> distinctIp = default, Option<VelocityData> distinctLinkedId = default, Option<VelocityData> distinctCountry = default, Option<VelocityData> events = default, Option<VelocityData> ipEvents = default, Option<VelocityData> distinctIpByLinkedId = default, Option<VelocityData> distinctVisitorIdByLinkedId = default)
        {
            DistinctIpOption = distinctIp;
            DistinctLinkedIdOption = distinctLinkedId;
            DistinctCountryOption = distinctCountry;
            EventsOption = events;
            IpEventsOption = ipEvents;
            DistinctIpByLinkedIdOption = distinctIpByLinkedId;
            DistinctVisitorIdByLinkedIdOption = distinctVisitorIdByLinkedId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of DistinctIp
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<VelocityData> DistinctIpOption { get; private set; }

        /// <summary>
        /// Gets or Sets DistinctIp
        /// </summary>
        [JsonPropertyName("distinct_ip")]
        public VelocityData DistinctIp { get { return this.DistinctIpOption; } set { this.DistinctIpOption = new Option<VelocityData>(value); } }

        /// <summary>
        /// Used to track the state of DistinctLinkedId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<VelocityData> DistinctLinkedIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets DistinctLinkedId
        /// </summary>
        [JsonPropertyName("distinct_linked_id")]
        public VelocityData DistinctLinkedId { get { return this.DistinctLinkedIdOption; } set { this.DistinctLinkedIdOption = new Option<VelocityData>(value); } }

        /// <summary>
        /// Used to track the state of DistinctCountry
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<VelocityData> DistinctCountryOption { get; private set; }

        /// <summary>
        /// Gets or Sets DistinctCountry
        /// </summary>
        [JsonPropertyName("distinct_country")]
        public VelocityData DistinctCountry { get { return this.DistinctCountryOption; } set { this.DistinctCountryOption = new Option<VelocityData>(value); } }

        /// <summary>
        /// Used to track the state of Events
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<VelocityData> EventsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Events
        /// </summary>
        [JsonPropertyName("events")]
        public VelocityData Events { get { return this.EventsOption; } set { this.EventsOption = new Option<VelocityData>(value); } }

        /// <summary>
        /// Used to track the state of IpEvents
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<VelocityData> IpEventsOption { get; private set; }

        /// <summary>
        /// Gets or Sets IpEvents
        /// </summary>
        [JsonPropertyName("ip_events")]
        public VelocityData IpEvents { get { return this.IpEventsOption; } set { this.IpEventsOption = new Option<VelocityData>(value); } }

        /// <summary>
        /// Used to track the state of DistinctIpByLinkedId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<VelocityData> DistinctIpByLinkedIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets DistinctIpByLinkedId
        /// </summary>
        [JsonPropertyName("distinct_ip_by_linked_id")]
        public VelocityData DistinctIpByLinkedId { get { return this.DistinctIpByLinkedIdOption; } set { this.DistinctIpByLinkedIdOption = new Option<VelocityData>(value); } }

        /// <summary>
        /// Used to track the state of DistinctVisitorIdByLinkedId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<VelocityData> DistinctVisitorIdByLinkedIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets DistinctVisitorIdByLinkedId
        /// </summary>
        [JsonPropertyName("distinct_visitor_id_by_linked_id")]
        public VelocityData DistinctVisitorIdByLinkedId { get { return this.DistinctVisitorIdByLinkedIdOption; } set { this.DistinctVisitorIdByLinkedIdOption = new Option<VelocityData>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Velocity {\n");
            sb.Append("  DistinctIp: ").Append(DistinctIp).Append("\n");
            sb.Append("  DistinctLinkedId: ").Append(DistinctLinkedId).Append("\n");
            sb.Append("  DistinctCountry: ").Append(DistinctCountry).Append("\n");
            sb.Append("  Events: ").Append(Events).Append("\n");
            sb.Append("  IpEvents: ").Append(IpEvents).Append("\n");
            sb.Append("  DistinctIpByLinkedId: ").Append(DistinctIpByLinkedId).Append("\n");
            sb.Append("  DistinctVisitorIdByLinkedId: ").Append(DistinctVisitorIdByLinkedId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Velocity" />
    /// </summary>
    public class VelocityJsonConverter : JsonConverter<Velocity>
    {
        /// <summary>
        /// Deserializes json to <see cref="Velocity" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Velocity Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<VelocityData> distinctIp = default;
            Option<VelocityData> distinctLinkedId = default;
            Option<VelocityData> distinctCountry = default;
            Option<VelocityData> events = default;
            Option<VelocityData> ipEvents = default;
            Option<VelocityData> distinctIpByLinkedId = default;
            Option<VelocityData> distinctVisitorIdByLinkedId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "distinct_ip":
                            distinctIp = new Option<VelocityData>(JsonSerializer.Deserialize<VelocityData>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "distinct_linked_id":
                            distinctLinkedId = new Option<VelocityData>(JsonSerializer.Deserialize<VelocityData>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "distinct_country":
                            distinctCountry = new Option<VelocityData>(JsonSerializer.Deserialize<VelocityData>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "events":
                            events = new Option<VelocityData>(JsonSerializer.Deserialize<VelocityData>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "ip_events":
                            ipEvents = new Option<VelocityData>(JsonSerializer.Deserialize<VelocityData>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "distinct_ip_by_linked_id":
                            distinctIpByLinkedId = new Option<VelocityData>(JsonSerializer.Deserialize<VelocityData>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "distinct_visitor_id_by_linked_id":
                            distinctVisitorIdByLinkedId = new Option<VelocityData>(JsonSerializer.Deserialize<VelocityData>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (distinctIp.IsSet && distinctIp.Value == null)
                throw new ArgumentNullException(nameof(distinctIp), "Property is not nullable for class Velocity.");

            if (distinctLinkedId.IsSet && distinctLinkedId.Value == null)
                throw new ArgumentNullException(nameof(distinctLinkedId), "Property is not nullable for class Velocity.");

            if (distinctCountry.IsSet && distinctCountry.Value == null)
                throw new ArgumentNullException(nameof(distinctCountry), "Property is not nullable for class Velocity.");

            if (events.IsSet && events.Value == null)
                throw new ArgumentNullException(nameof(events), "Property is not nullable for class Velocity.");

            if (ipEvents.IsSet && ipEvents.Value == null)
                throw new ArgumentNullException(nameof(ipEvents), "Property is not nullable for class Velocity.");

            if (distinctIpByLinkedId.IsSet && distinctIpByLinkedId.Value == null)
                throw new ArgumentNullException(nameof(distinctIpByLinkedId), "Property is not nullable for class Velocity.");

            if (distinctVisitorIdByLinkedId.IsSet && distinctVisitorIdByLinkedId.Value == null)
                throw new ArgumentNullException(nameof(distinctVisitorIdByLinkedId), "Property is not nullable for class Velocity.");

            return new Velocity(distinctIp, distinctLinkedId, distinctCountry, events, ipEvents, distinctIpByLinkedId, distinctVisitorIdByLinkedId);
        }

        /// <summary>
        /// Serializes a <see cref="Velocity" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="velocity"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Velocity velocity, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, velocity, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Velocity" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="velocity"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Velocity velocity, JsonSerializerOptions jsonSerializerOptions)
        {
            if (velocity.DistinctIpOption.IsSet && velocity.DistinctIp == null)
                throw new ArgumentNullException(nameof(velocity.DistinctIp), "Property is required for class Velocity.");

            if (velocity.DistinctLinkedIdOption.IsSet && velocity.DistinctLinkedId == null)
                throw new ArgumentNullException(nameof(velocity.DistinctLinkedId), "Property is required for class Velocity.");

            if (velocity.DistinctCountryOption.IsSet && velocity.DistinctCountry == null)
                throw new ArgumentNullException(nameof(velocity.DistinctCountry), "Property is required for class Velocity.");

            if (velocity.EventsOption.IsSet && velocity.Events == null)
                throw new ArgumentNullException(nameof(velocity.Events), "Property is required for class Velocity.");

            if (velocity.IpEventsOption.IsSet && velocity.IpEvents == null)
                throw new ArgumentNullException(nameof(velocity.IpEvents), "Property is required for class Velocity.");

            if (velocity.DistinctIpByLinkedIdOption.IsSet && velocity.DistinctIpByLinkedId == null)
                throw new ArgumentNullException(nameof(velocity.DistinctIpByLinkedId), "Property is required for class Velocity.");

            if (velocity.DistinctVisitorIdByLinkedIdOption.IsSet && velocity.DistinctVisitorIdByLinkedId == null)
                throw new ArgumentNullException(nameof(velocity.DistinctVisitorIdByLinkedId), "Property is required for class Velocity.");

            if (velocity.DistinctIpOption.IsSet)
            {
                writer.WritePropertyName("distinct_ip");
                JsonSerializer.Serialize(writer, velocity.DistinctIp, jsonSerializerOptions);
            }
            if (velocity.DistinctLinkedIdOption.IsSet)
            {
                writer.WritePropertyName("distinct_linked_id");
                JsonSerializer.Serialize(writer, velocity.DistinctLinkedId, jsonSerializerOptions);
            }
            if (velocity.DistinctCountryOption.IsSet)
            {
                writer.WritePropertyName("distinct_country");
                JsonSerializer.Serialize(writer, velocity.DistinctCountry, jsonSerializerOptions);
            }
            if (velocity.EventsOption.IsSet)
            {
                writer.WritePropertyName("events");
                JsonSerializer.Serialize(writer, velocity.Events, jsonSerializerOptions);
            }
            if (velocity.IpEventsOption.IsSet)
            {
                writer.WritePropertyName("ip_events");
                JsonSerializer.Serialize(writer, velocity.IpEvents, jsonSerializerOptions);
            }
            if (velocity.DistinctIpByLinkedIdOption.IsSet)
            {
                writer.WritePropertyName("distinct_ip_by_linked_id");
                JsonSerializer.Serialize(writer, velocity.DistinctIpByLinkedId, jsonSerializerOptions);
            }
            if (velocity.DistinctVisitorIdByLinkedIdOption.IsSet)
            {
                writer.WritePropertyName("distinct_visitor_id_by_linked_id");
                JsonSerializer.Serialize(writer, velocity.DistinctVisitorIdByLinkedId, jsonSerializerOptions);
            }
        }
    }
}
