// <auto-generated>
/* 
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Fingerprint.ServerSdk.Client;

namespace Fingerprint.ServerSdk.Model
{
    /// <summary>
    /// A confidence rating for the VPN detection result — \&quot;low\&quot;, \&quot;medium\&quot;, or \&quot;high\&quot;. Depends on the combination of results returned from all VPN detection methods.
    /// </summary>
    /// <value>A confidence rating for the VPN detection result — \&quot;low\&quot;, \&quot;medium\&quot;, or \&quot;high\&quot;. Depends on the combination of results returned from all VPN detection methods.</value>
    public enum VpnConfidence
    {
        /// <summary>
        /// Enum Low for value: low
        /// </summary>
        Low = 1,

        /// <summary>
        /// Enum Medium for value: medium
        /// </summary>
        Medium = 2,

        /// <summary>
        /// Enum High for value: high
        /// </summary>
        High = 3
    }

    /// <summary>
    /// Converts <see cref="VpnConfidence"/> to and from the JSON value
    /// </summary>
    public static class VpnConfidenceValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="VpnConfidence"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static VpnConfidence FromString(string value)
        {
            if (value.Equals("low"))
                return VpnConfidence.Low;

            if (value.Equals("medium"))
                return VpnConfidence.Medium;

            if (value.Equals("high"))
                return VpnConfidence.High;

            throw new NotImplementedException($"Could not convert value to type VpnConfidence: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="VpnConfidence"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static VpnConfidence? FromStringOrDefault(string value)
        {
            if (value.Equals("low"))
                return VpnConfidence.Low;

            if (value.Equals("medium"))
                return VpnConfidence.Medium;

            if (value.Equals("high"))
                return VpnConfidence.High;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="VpnConfidence"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(VpnConfidence value)
        {
            if (value == VpnConfidence.Low)
                return "low";

            if (value == VpnConfidence.Medium)
                return "medium";

            if (value == VpnConfidence.High)
                return "high";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="VpnConfidence"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class VpnConfidenceJsonConverter : JsonConverter<VpnConfidence>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override VpnConfidence Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            VpnConfidence? result = rawValue == null
                ? null
                : VpnConfidenceValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the VpnConfidence to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="vpnConfidence"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, VpnConfidence vpnConfidence, JsonSerializerOptions options)
        {
            writer.WriteStringValue(VpnConfidenceValueConverter.ToJsonValue(vpnConfidence).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="VpnConfidence"/>
    /// </summary>
    public class VpnConfidenceNullableJsonConverter : JsonConverter<VpnConfidence?>
    {
        /// <summary>
        /// Returns a VpnConfidence from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override VpnConfidence? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            VpnConfidence? result = rawValue == null
                ? null
                : VpnConfidenceValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the VpnConfidence to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="vpnConfidence"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, VpnConfidence? vpnConfidence, JsonSerializerOptions options)
        {
            writer.WriteStringValue(vpnConfidence.HasValue ? VpnConfidenceValueConverter.ToJsonValue(vpnConfidence.Value).ToString() : "null");
        }
    }
}
