/* 
 * Fingerprint Pro Server API
 *
 * Fingerprint Pro Server API allows you to get information about visitors and about individual events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * OpenAPI spec version: 3
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Text;
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace FingerprintPro.ServerSdk.Model
{
    /// <summary>
    /// IpBlockListResult
    /// </summary>
    [DataContract]
    public class IpBlockListResult : IEquatable<IpBlockListResult>
    {


        /// <summary>
        /// Initializes a new instance of the <see cref="IpBlockListResult" /> class.
        /// </summary>
        /// <param name="result">`true` if request IP address is part of any database that we use to search for known malicious actors, `false` otherwise.  (required).</param>
        /// <param name="details">details (required).</param>
        public IpBlockListResult(bool? result = default(bool?), IpBlockListResultDetails details = default(IpBlockListResultDetails))
        {
            // to ensure "result" is required (not null)
            // swagger debug: IpBlockListResult Result

            if (result == null)
            {
                throw new InvalidDataException("result is a required property for IpBlockListResult and cannot be null");
            }
            else
            {
                this.Result = result;
            }
            // to ensure "details" is required (not null)
            // swagger debug: IpBlockListResult Details

            if (details == null)
            {
                throw new InvalidDataException("details is a required property for IpBlockListResult and cannot be null");
            }
            else
            {
                this.Details = details;
            }
        }

        /// <summary>
        /// `true` if request IP address is part of any database that we use to search for known malicious actors, `false` otherwise. 
        /// </summary>
        /// <value>`true` if request IP address is part of any database that we use to search for known malicious actors, `false` otherwise. </value>
        [DataMember(Name = "result", EmitDefaultValue = false)]
        [JsonPropertyName("result")]
        public bool? Result { get; set; }

        /// <summary>
        /// Gets or Sets Details
        /// </summary>
        [DataMember(Name = "details", EmitDefaultValue = false)]
        [JsonPropertyName("details")]
        public IpBlockListResultDetails Details { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class IpBlockListResult {\n");
            sb.Append("  Result: ").Append(Result).Append("\n");
            sb.Append("  Details: ").Append(Details).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            var options = new JsonSerializerOptions
            {
                WriteIndented = true
            };

            return JsonSerializer.Serialize(this, options);
        }

        /// <summary>
        /// Returns true if IpBlockListResult instances are equal
        /// </summary>
        /// <param name="input">Instance of IpBlockListResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(IpBlockListResult input)
        {
            if (input == null)
                return false;

            return
                (
                this.Result == input.Result ||
                (this.Result != null &&
                this.Result.Equals(input.Result))
                ) &&
                (
                this.Details == input.Details ||
                (this.Details != null &&
                this.Details.Equals(input.Details))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Result != null)
                    hashCode = hashCode * 59 + this.Result.GetHashCode();
                if (this.Details != null)
                    hashCode = hashCode * 59 + this.Details.GetHashCode();
                return hashCode;
            }
        }

    }
}
