/* 
 * Fingerprint Pro Server API
 *
 * Fingerprint Pro Server API allows you to get information about visitors and about individual events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * OpenAPI spec version: 3
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Text;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace FingerprintPro.ServerSdk.Model
{
    /// <summary>
    /// TamperingResult
    /// </summary>
    [DataContract]
    public partial class TamperingResult : IEquatable<TamperingResult>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TamperingResult" /> class.
        /// </summary>
        /// <param name="result">Flag indicating whether browser tampering was detected according to our internal thresholds..</param>
        /// <param name="anomalyScore">Confidence score (`0.0 - 1.0`) for the tampering detection. Values above `0.5` suggest that we're reasonably sure there was a tampering attempt. Values below `0.5` are genuine browsers..</param>
        public TamperingResult(bool? result = default(bool?), decimal? anomalyScore = default(decimal?))
        {
            this.Result = result;
            this.AnomalyScore = anomalyScore;
        }

        /// <summary>
        /// Flag indicating whether browser tampering was detected according to our internal thresholds.
        /// </summary>
        /// <value>Flag indicating whether browser tampering was detected according to our internal thresholds.</value>
        [DataMember(Name = "result", EmitDefaultValue = false)]
        public bool? Result { get; set; }

        /// <summary>
        /// Confidence score (`0.0 - 1.0`) for the tampering detection. Values above `0.5` suggest that we're reasonably sure there was a tampering attempt. Values below `0.5` are genuine browsers.
        /// </summary>
        /// <value>Confidence score (`0.0 - 1.0`) for the tampering detection. Values above `0.5` suggest that we're reasonably sure there was a tampering attempt. Values below `0.5` are genuine browsers.</value>
        [DataMember(Name = "anomalyScore", EmitDefaultValue = false)]
        public decimal? AnomalyScore { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TamperingResult {\n");
            sb.Append("  Result: ").Append(Result).Append("\n");
            sb.Append("  AnomalyScore: ").Append(AnomalyScore).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if TamperingResult instances are equal
        /// </summary>
        /// <param name="input">Instance of TamperingResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TamperingResult input)
        {
            if (input == null)
                return false;

            return
                (
                this.Result == input.Result ||
                (this.Result != null &&
                this.Result.Equals(input.Result))
                ) &&
                (
                this.AnomalyScore == input.AnomalyScore ||
                (this.AnomalyScore != null &&
                this.AnomalyScore.Equals(input.AnomalyScore))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Result != null)
                    hashCode = hashCode * 59 + this.Result.GetHashCode();
                if (this.AnomalyScore != null)
                    hashCode = hashCode * 59 + this.AnomalyScore.GetHashCode();
                return hashCode;
            }
        }

    }
}