/* 
 * Fingerprint Pro Server API
 *
 * Fingerprint Pro Server API allows you to get information about visitors and about individual events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * OpenAPI spec version: 3
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Text;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace FingerprintPro.ServerSdk.Model
{
    /// <summary>
    /// VpnResult
    /// </summary>
    [DataContract]
    public partial class VpnResult : IEquatable<VpnResult>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VpnResult" /> class.
        /// </summary>
        /// <param name="result">VPN or other anonymising service has been used when sending the request..</param>
        /// <param name="methods">methods.</param>
        public VpnResult(bool? result = default(bool?), VpnResultMethods methods = default(VpnResultMethods))
        {
            this.Result = result;
            this.Methods = methods;
        }

        /// <summary>
        /// VPN or other anonymising service has been used when sending the request.
        /// </summary>
        /// <value>VPN or other anonymising service has been used when sending the request.</value>
        [DataMember(Name = "result", EmitDefaultValue = false)]
        public bool? Result { get; set; }

        /// <summary>
        /// Gets or Sets Methods
        /// </summary>
        [DataMember(Name = "methods", EmitDefaultValue = false)]
        public VpnResultMethods Methods { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VpnResult {\n");
            sb.Append("  Result: ").Append(Result).Append("\n");
            sb.Append("  Methods: ").Append(Methods).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if VpnResult instances are equal
        /// </summary>
        /// <param name="input">Instance of VpnResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VpnResult input)
        {
            if (input == null)
                return false;

            return
                (
                this.Result == input.Result ||
                (this.Result != null &&
                this.Result.Equals(input.Result))
                ) &&
                (
                this.Methods == input.Methods ||
                (this.Methods != null &&
                this.Methods.Equals(input.Methods))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Result != null)
                    hashCode = hashCode * 59 + this.Result.GetHashCode();
                if (this.Methods != null)
                    hashCode = hashCode * 59 + this.Methods.GetHashCode();
                return hashCode;
            }
        }

    }
}