/* 
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * OpenAPI spec version: 3
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Text;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;
using System.Text.Json;
using FingerprintPro.ServerSdk.Json;

namespace FingerprintPro.ServerSdk.Model
{
    /// <summary>
    /// WebhookLocationSpoofing
    /// </summary>
    [DataContract]
    public class WebhookLocationSpoofing : IEquatable<WebhookLocationSpoofing>
    {


        /// <summary>
        /// Initializes a new instance of the <see cref="WebhookLocationSpoofing" /> class.
        /// </summary>
        /// <param name="result">Flag indicating whether the request came from a mobile device with location spoofing enabled..</param>
        public WebhookLocationSpoofing(bool? result = default(bool?))
        {
            this.Result = result;
        }

        /// <summary>
        /// Flag indicating whether the request came from a mobile device with location spoofing enabled.
        /// </summary>
        /// <value>Flag indicating whether the request came from a mobile device with location spoofing enabled.</value>
        [DataMember(Name = "result", EmitDefaultValue = false)]
        [JsonPropertyName("result")]
        public bool? Result { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WebhookLocationSpoofing {\n");
            sb.Append("  Result: ").Append(Result).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonUtils.Serialize(this);
        }

        /// <summary>
        /// Returns true if WebhookLocationSpoofing instances are equal
        /// </summary>
        /// <param name="input">Instance of WebhookLocationSpoofing to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WebhookLocationSpoofing? input)
        {
            if (input == null)
                return false;

            return
                (
                this.Result == input.Result ||
                (this.Result != null &&
                this.Result.Equals(input.Result))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Result != null)
                    hashCode = hashCode * 59 + this.Result.GetHashCode();
                return hashCode;
            }
        }

    }
}
