/* 
 * Fingerprint Pro Server API
 *
 * Fingerprint Pro Server API allows you to get information about visitors and about individual events in a server environment. This API can be used for data exports, decision-making, and data analysis scenarios.
 *
 * OpenAPI spec version: 3
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using sdk.Api;
using sdk.Model;
using sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace sdk.Test
{
    /// <summary>
    ///  Class for testing BrowserDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BrowserDetailsTests
    {
        // TODO uncomment below to declare an instance variable for BrowserDetails
        //private BrowserDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BrowserDetails
            //instance = new BrowserDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BrowserDetails
        /// </summary>
        [Test]
        public void BrowserDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BrowserDetails
            //Assert.IsInstanceOfType<BrowserDetails> (instance, "variable 'instance' is a BrowserDetails");
        }


        /// <summary>
        /// Test the property 'BrowserName'
        /// </summary>
        [Test]
        public void BrowserNameTest()
        {
            // TODO unit test for the property 'BrowserName'
        }
        /// <summary>
        /// Test the property 'BrowserMajorVersion'
        /// </summary>
        [Test]
        public void BrowserMajorVersionTest()
        {
            // TODO unit test for the property 'BrowserMajorVersion'
        }
        /// <summary>
        /// Test the property 'BrowserFullVersion'
        /// </summary>
        [Test]
        public void BrowserFullVersionTest()
        {
            // TODO unit test for the property 'BrowserFullVersion'
        }
        /// <summary>
        /// Test the property 'Os'
        /// </summary>
        [Test]
        public void OsTest()
        {
            // TODO unit test for the property 'Os'
        }
        /// <summary>
        /// Test the property 'OsVersion'
        /// </summary>
        [Test]
        public void OsVersionTest()
        {
            // TODO unit test for the property 'OsVersion'
        }
        /// <summary>
        /// Test the property 'Device'
        /// </summary>
        [Test]
        public void DeviceTest()
        {
            // TODO unit test for the property 'Device'
        }
        /// <summary>
        /// Test the property 'UserAgent'
        /// </summary>
        [Test]
        public void UserAgentTest()
        {
            // TODO unit test for the property 'UserAgent'
        }
        /// <summary>
        /// Test the property 'BotProbability'
        /// </summary>
        [Test]
        public void BotProbabilityTest()
        {
            // TODO unit test for the property 'BotProbability'
        }

    }

}
