/* 
 * Fingerprint Pro Server API
 *
 * Fingerprint Pro Server API allows you to get information about visitors and about individual events in a server environment. This API can be used for data exports, decision-making, and data analysis scenarios.
 *
 * OpenAPI spec version: 3
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using sdk.Api;
using sdk.Model;
using sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace sdk.Test
{
    /// <summary>
    ///  Class for testing Confidence
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ConfidenceTests
    {
        // TODO uncomment below to declare an instance variable for Confidence
        //private Confidence instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Confidence
            //instance = new Confidence();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Confidence
        /// </summary>
        [Test]
        public void ConfidenceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Confidence
            //Assert.IsInstanceOfType<Confidence> (instance, "variable 'instance' is a Confidence");
        }


        /// <summary>
        /// Test the property 'Score'
        /// </summary>
        [Test]
        public void ScoreTest()
        {
            // TODO unit test for the property 'Score'
        }

    }

}
