/* 
 * Fingerprint Pro Server API
 *
 * Fingerprint Pro Server API allows you to get information about visitors and about individual events in a server environment. This API can be used for data exports, decision-making, and data analysis scenarios.
 *
 * OpenAPI spec version: 3
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using sdk.Api;
using sdk.Model;
using sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace sdk.Test
{
    /// <summary>
    ///  Class for testing Subdivision
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SubdivisionTests
    {
        // TODO uncomment below to declare an instance variable for Subdivision
        //private Subdivision instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Subdivision
            //instance = new Subdivision();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Subdivision
        /// </summary>
        [Test]
        public void SubdivisionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Subdivision
            //Assert.IsInstanceOfType<Subdivision> (instance, "variable 'instance' is a Subdivision");
        }


        /// <summary>
        /// Test the property 'IsoCode'
        /// </summary>
        [Test]
        public void IsoCodeTest()
        {
            // TODO unit test for the property 'IsoCode'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
