/* 
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.DependencyInjection;
using System.Linq;
using System.Net.Http.Headers;
using Fingerprint.ServerSdk.Client;
using Fingerprint.ServerSdk.Api;
using Fingerprint.ServerSdk.Extensions;
using Xunit;

namespace Fingerprint.ServerSdk.Test.Api
{
    /// <summary>
    ///  Tests the dependency injection.
    /// </summary>
    public class DependencyInjectionTest
    {

        private const string Token = "<token>";

        private const string CustomUserAgentProduct = "custom-user-agent";

        private const string CustomUserAgentVersion = "1.0.0";

        private const string CustomUserAgent = $"{CustomUserAgentProduct}/{CustomUserAgentVersion}";

        private readonly IHost _hostUsingConfigureWithoutAClient =
            Host.CreateDefaultBuilder([]).ConfigureApi((_, _, options) =>
            {
                var bearerToken1 = new BearerToken(Token);
                options.AddTokens(bearerToken1);
            })
            .Build();

        private readonly IHost _hostUsingConfigureWithAClient =
            Host.CreateDefaultBuilder([]).ConfigureApi((_, _, options) =>
            {
                var bearerToken1 = new BearerToken(Token);
                options.AddTokens(bearerToken1);
                options.AddApiHttpClients(client => client.BaseAddress = ClientUtils.GetBaseUri(Region.Us));
            })
            .Build();

        private readonly IHost _hostUsingAddWithoutAClient =
            Host.CreateDefaultBuilder([]).ConfigureServices((_, services) =>
            {
                services.AddApi(options =>
                {
                    var bearerToken1 = new BearerToken(Token);
                    options.AddTokens(bearerToken1);
                });
            })
            .Build();

        private readonly IHost _hostUsingAddWithAClient =
            Host.CreateDefaultBuilder([]).ConfigureServices((_, services) =>
            {
                services.AddApi(options =>
                {
                    var bearerToken1 = new BearerToken(Token);
                    options.AddTokens(bearerToken1);
                    options.AddApiHttpClients(client => client.BaseAddress = ClientUtils.GetBaseUri(Region.Us));
                });
            })
            .Build();


        private readonly IHost _hostUsingDifferentUserAgent =
            Host.CreateDefaultBuilder([]).ConfigureServices((_, services) =>
                {
                    services.AddApi(options =>
                    {
                        options.UserAgent = CustomUserAgent;

                        var bearerToken1 = new BearerToken(Token);
                        options.AddTokens(bearerToken1);
                    });
                })
                .Build();

        /// <summary>
        /// Test dependency injection when using the configure method
        /// </summary>
        [Fact]
        public void ConfigureApiWithAClientTest()
        {
            var fingerprintApi = _hostUsingConfigureWithAClient.Services.GetRequiredService<IFingerprintApi>();
            Assert.True(fingerprintApi.HttpClient.BaseAddress != null);
        }

        /// <summary>
        /// Test dependency injection when using the configure method
        /// </summary>
        [Fact]
        public void ConfigureApiWithoutAClientTest()
        {
            var fingerprintApi = _hostUsingConfigureWithoutAClient.Services.GetRequiredService<IFingerprintApi>();
            Assert.True(fingerprintApi.HttpClient.BaseAddress != null);
        }

        /// <summary>
        /// Test custom user agent
        /// </summary>
        [Fact]
        public void ConfigureApiWithCustomUserAgentTest()
        {
            var fingerprintApi = _hostUsingDifferentUserAgent.Services.GetRequiredService<IFingerprintApi>();
            var userAgentCollection = fingerprintApi.HttpClient.DefaultRequestHeaders.UserAgent;
            Assert.Single(userAgentCollection);
            var userAgent = userAgentCollection.First();
            Assert.Equal(new ProductInfoHeaderValue(CustomUserAgentProduct, CustomUserAgentVersion), userAgent);
        }

        /// <summary>
        /// Test dependency injection when using the add method
        /// </summary>
        [Fact]
        public void AddApiWithAClientTest()
        {
            var fingerprintApi = _hostUsingAddWithAClient.Services.GetRequiredService<IFingerprintApi>();
            Assert.True(fingerprintApi.HttpClient.BaseAddress != null);
        }

        /// <summary>
        /// Test dependency injection when using the add method
        /// </summary>
        [Fact]
        public void AddApiWithoutAClientTest()
        {
            var fingerprintApi = _hostUsingAddWithoutAClient.Services.GetRequiredService<IFingerprintApi>();
            Assert.True(fingerprintApi.HttpClient.BaseAddress != null);
        }
    }
}